# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/tracker120',
                'doc_host': 'https://prabhanshu11.github.io',
                'git_url': 'https://github.com/prabhanshu11/tracker120',
                'lib_path': 'tracker120'},
  'syms': {'tracker120.core': {'tracker120.core.foo': ('core.html#foo', 'tracker120/core.py')}}}