ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "tracker120"
  site-url: "https://prabhanshu11.github.io/tracker120"
  description: "An app which overlays daily git activity in a box on desktop wallpaper."
  twitter-card: true
  open-graph: true
  repo-branch: master
  repo-url: "https://github.com/prabhanshu11/tracker120"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/prabhanshu11/tracker120"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
